{
 "title": "Health dashboard (merged)",
 "time": { "from": "now-6y", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "influxdb" }
  ]
 },
 "panels": [
  { "title": "Weight", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Weight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "measurement": "user",
     "query": "SELECT mean(\"weight\") FROM \"user\" WHERE (\"weight\"::field > 40) AND $timeFilter GROUP BY time(1d) fill(previous)"
    },
    {
     "measurement": "user",
     "query": "SELECT mean(\"weight\") FROM \"user\" WHERE (\"weight\"::field > 40) AND $timeFilter GROUP BY time(30d) fill(previous)"
    }
   ]
  },
  {
   "title": "Weight moving average derivative",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "alias": "Yearly moving average",
     "measurement": "user",
     "query": "SELECT derivative(mean(\"weight\")) FROM \"user\" WHERE   $timeFilter GROUP BY time(30d) "
    }
   ]
  },
  { "title": "Actively Tracked", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Minutes asleep per day",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "alias": "Total minutes asleep",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "sleepsummaries",
     "select": [
      [
       { "params": [ "totalMinutesAsleep" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "totalMinutesAsleep::field", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "total 30d moving average ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sleepsummaries",
     "select": [
      [
       { "params": [ "totalMinutesAsleep" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         30
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Deep Sleep per day",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "alias": "Deep",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "sleepsummaries",
     "select": [
      [
       { "params": [ "stages.deep" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Deep 30d moving average",
     "measurement": "sleepsummaries",
     "query": "SELECT moving_average(mean(\"stages.deep\"), 30) FROM \"sleepsummaries\" WHERE $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "Resting heartrate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1w" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "activities",
     "select": [
      [
       { "params": [ "restingHeartRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "30dma",
     "measurement": "activities",
     "query": "SELECT moving_average(mean( \"restingHeartRate\"), 30) FROM \"activities\" WHERE $timeFilter GROUP BY time(1w) fill(null)"
    }
   ]
  },
  {
   "title": "Sleep stages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "alias": "deep",
     "groupBy": [
      { "params": [ "1w" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sleepsummaries",
     "select": [
      [
       { "params": [ "stages.deep" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "light",
     "groupBy": [
      { "params": [ "1w" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sleepsummaries",
     "select": [
      [
       { "params": [ "stages.light" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "rem",
     "groupBy": [
      { "params": [ "1w" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sleepsummaries",
     "select": [
      [
       { "params": [ "stages.rem" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "wake",
     "groupBy": [
      { "params": [ "1w" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sleepsummaries",
     "select": [
      [
       { "params": [ "stages.wake" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Yearly total sleep moving average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "alias": "Total 365d moving average",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sleepsummaries",
     "select": [
      [
       { "params": [ "totalMinutesAsleep" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "365" ], "type": "moving_average" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Minutes of activity",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "alias": "Very active",
     "groupBy": [
      { "params": [ "7d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "activities",
     "select": [
      [
       { "params": [ "veryActiveMinutes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Moderately active",
     "groupBy": [
      { "params": [ "7d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "activities",
     "select": [
      [
       { "params": [ "fairlyActiveMinutes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Lightly active",
     "groupBy": [
      { "params": [ "7d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "activities",
     "select": [
      [
       { "params": [ "lightlyActiveMinutes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Active (Pebble)",
     "measurement": "activities",
     "query": "SELECT mean(\"activeMinutes\") FROM \"activities\" WHERE $timeFilter GROUP BY time(7d) fill(null)",
     "groupBy": [
      { "params": [ "7d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "activeMinutes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily steps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "alias": "Daily steps",
     "measurement": "activities",
     "query": "SELECT mean(\"steps\") FROM \"activities\" WHERE $timeFilter GROUP BY time(1d) fill(null)",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "steps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "365d moving average",
     "measurement": "activities",
     "query": "SELECT moving_average(mean(\"steps\"), 365) FROM \"activities\" WHERE $timeFilter GROUP BY time(1d) fill(null)",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "steps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "365" ], "type": "moving_average" }
      ]
     ]
    }
   ]
  },
  {
   "title": "archive",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heart Rate Peter",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "heartrate",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "heartrate",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "7" ], "type": "moving_average" }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}